### ISSUE TITLE
Add older versions?

### ISSUE THREAD

**Issue by rstacruz** [aredridel/homebrew-iojs#23]
It would be nice to be able to install older iojs versions, especially since v3.0.0 breaks many existing packages. This can be kept in a separate repository (`homebrew-iojs-versions`?)

**Comment by bcomnes** [comment]
You can already do this! http://stackoverflow.com/questions/13477363/how-can-i-brew-link-a-specific-version

`brew swich` lets you link in previously installed versions of anything.

If you need a version in the past that wasn't ever installed, cd to `/usr/local`, navigate to the tap and checkout the version with the correct formula, install that, the checkout HEAD again.  

Does that work?  Otherwise, I'm not totally opposed to a `iojs-versions` tap.
